version: "3.2"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - ./backend:/api
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm start
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
